In [67]:
import pymatgen as mp
import numpy as np
import pymatgen.symmetry.analyzer as span
import pymatgen.core.lattice as lat
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from pymatgen.ext.matproj import MPRester
with MPRester("tA2HQFkWnG7wRPHf") as api:
    structure=api.get_structure_by_material_id("mp-7959")
print(structure)
finder = span.SpacegroupAnalyzer(structure)
new_finder=finder.get_primitive_standard_structure()
my_lattice=new_finder.lattice
vol=structure.volume
alpha=my_lattice.alpha
beta=my_lattice.beta
gamma=my_lattice.gamma
t1=my_lattice.a
t2=my_lattice.b
t3=my_lattice.c
a=[my_lattice.a,0,0]
b=[t1*t2*np.cos(alpha),t1*t2*np.sin(alpha),0]
c=[t1*t3*np.cos(gamma),t2*t3*np.cos(beta),t2*t3*np.sin(beta)]
a=a/np.linalg.norm(a)
b=b/np.linalg.norm(b)
c=c/np.linalg.norm(c)
a1=(2*np.pi)/vol*np.cross(b,c)
b1=(2*np.pi)/vol*np.cross(c,a)
c1=(2*np.pi)/vol*np.cross(a,b)
print(' ')
print('Base vectors ')
print(a)
print(b)
print(c)
print(' ')
print('Reciprocal base vectors ')
print(a1)
print(b1)
print(c1)
print(' ')
print('crystal system:')
print(finder.get_crystal_system())
print(' ')
print('latice type:')
print(finder.get_lattice_type())
print(' ')
print('space group symbol')
print(finder.get_space_group_symbol())
print(' ')
print('reciprocal mesh:')
print(finder.get_ir_reciprocal_mesh(mesh=(3, 3, 3), is_shift=(0, 0, 0)))
print(' ')
#print('symmetry operations:')
#finder.get_symmetry_operations()

Full Formula (K1 Er1 O2)
Reduced Formula: KErO2
abc   :   6.560674   6.560674   6.560674
angles:  30.451816  30.451816  30.451816
Sites (4)
  #  SP           a         b         c    magmom
---  ----  --------  --------  --------  --------
  0  O     0.772128  0.772128  0.772128         0
  1  O     0.227872  0.227872  0.227872         0
  2  K     0         0         0                0
  3  Er    0.5       0.5       0.5              0
 
Base vectors 
[1. 0. 0.]
[ 0.57014809 -0.82154194  0.        ]
[ 0.49530014  0.49530014 -0.71369149]
 
Reciprocal base vectors 
[0.05730052 0.03976642 0.06736422]
[ 0.         -0.06974753 -0.04840462]
[ 0.          0.         -0.08028753]
 
crystal system:
trigonal
 
latice type:
rhombohedral
 
space group symbol
R-3m
 
reciprocal mesh:
[(array([0., 0., 0.]), 1), (array([0.33333333, 0.        , 0.        ]), 6), (array([0.33333333, 0.33333333, 0.        ]), 6), (array([-0.33333333,  0.33333333,  0.        ]), 6), (array([0.33333333, 0.33333333, 0.33333