In [14]:
import pymatgen as mp
import numpy as np
import pymatgen.symmetry.analyzer as span
import pymatgen.core.lattice as lat
from pymatgen.core.operations import SymmOp
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from pymatgen.ext.matproj import MPRester
with MPRester("tA2HQFkWnG7wRPHf") as api:
    structure=api.get_structure_by_material_id("mp-7959")
print(structure)
finder = span.SpacegroupAnalyzer(structure)
print("")
mirror=SymmOp.from_xyz_string("-y,-x,z")
print("L’élément de symétrie n°8 du fichier CIF est un plan miroir perpendiculaire à la direction[110]")
print("Cet élément de symétrie envoie tout atome situé en(x,y,z)surun atome équivalent situé en(−x,-y,z)")
print("La matrice qui lui est associée est :")
print(mirror.rotation_matrix)
print("Son application à un atome de K situé en(2/3,1/3,1/3) est donné par l'atome équivalent:", mirror.operate((0.67,0.33,0.33)))
print("Voir fichier no8.jpg")

print("")

fsa=SymmOp.from_xyz_string("−y-1/3,x-y+1/3,z+1/3")
print("L’élément de symétrie n°15 du fichier CIF est une rotation hélicoïdale d'ordre 3.")
print("Cet élément de symétrie envoie tout atome situé en(x,y,z)surun atome équivalent situé en(−y-1/3,x-y+1/3,z+1/3)")
print("La matrice de rotation qui lui est associée est :")
print(fsa.rotation_matrix)
print("Le vecteur de transaltion qui lui est associée est :")
print([-1/3,1/3,1/3])
print("Son application à un atome de Er situé en(0,0,1/2) est donné par l'atome équivalent:", fsa.operate((0,0,0.5)))
print("Voir fichier no15.jpg")

print("")

translation=SymmOp.from_xyz_string("x+1/3,y-1/3,z-1/3")
print("L’élément de symétrie n°25 du fichier CIF est une translation.")
print("Cet élément de symétrie envoie tout atome situé en(x,y,z)surun atome équivalent situé en (x+1/3,y-1/3,z-1/3)")
print([1/3,-1/3,-1/3])
print("Son application à un atome de O2 situé en(0,0,0.23) est donné par l'atome équivalent:", translation.operate((0,0,0.23)))
print("Voir fichier no25.jpg")




Full Formula (K1 Er1 O2)
Reduced Formula: KErO2
abc   :   6.560674   6.560674   6.560674
angles:  30.451816  30.451816  30.451816
Sites (4)
  #  SP           a         b         c    magmom
---  ----  --------  --------  --------  --------
  0  O     0.772128  0.772128  0.772128         0
  1  O     0.227872  0.227872  0.227872         0
  2  K     0         0         0                0
  3  Er    0.5       0.5       0.5              0

L’élément de symétrie n°8 du fichier CIF est un plan miroir perpendiculaire à la direction[110]
Cet élément de symétrie envoie tout atome situé en(x,y,z)surun atome équivalent situé en(−x,-y,z)
La matrice qui lui est associée est :
[[ 0. -1.  0.]
 [-1.  0.  0.]
 [ 0.  0.  1.]]
Son application à un atome de K situé en(2/3,1/3,1/3) est donné par l'atome équivalent: [-0.33 -0.67  0.33]


NameError: name 'no15' is not defined