In [2]:
from pymatgen.symmetry import analyzer
from numpy import dot
from IPython.display import Image
from pymatgen.ext.matproj import MPRester
from pymatgen.io.cif import CifWriter

with MPRester("tA2HQFkWnG7wRPHf") as mp:
    # Create a structure for material id mp-23209
    structure = mp.get_structure_by_material_id("mp-23209")
    print(structure)
    

w = CifWriter(structure, symprec=0.1)
w.write_file("SrCl2_mp-23209.cif")


#SpacegroupAnalyser SGA:
SGA = analyzer.SpacegroupAnalyzer(structure)

SGO = SGA.get_space_group_operations()
print(SGO)

symop = SGA.get_symmetry_operations()
site = structure.sites
print("\nThe following data is pertinant to the study of our material.\n")
print("Carthesian Coordinates and fractional coordinates of the 3 atomes: \n")
print(site[0],site[0].frac_coords)
print("\n",site[1],site[1].frac_coords)
print("\n",site[2],site[2].frac_coords)

Full Formula (Sr1 Cl2)
Reduced Formula: SrCl2
abc   :   4.983141   4.983141   4.983141
angles:  60.000000  60.000000  60.000000
Sites (3)
  #  SP       a     b     c    magmom
---  ----  ----  ----  ----  --------
  0  Sr    0     0     0           -0
  1  Cl    0.75  0.75  0.75         0
  2  Cl    0.25  0.25  0.25         0
Fm-3m (225) spacegroup

The following data is pertinant to the study of our material.

Carthesian Coordinates and fractional coordinates of the 3 atomes: 

[0. 0. 0.] Sr [0. 0. 0.]

 [5.2854195 5.2854195 5.2854195] Cl [0.75 0.75 0.75]

 [1.7618065 1.7618065 1.7618065] Cl [0.25 0.25 0.25]


In [24]:
#
symop1 = symop[16] 
rot1 = symop1.rotation_matrix
transl1 = symop1.translation_vector
print("roto-inversion")
print("\nrotation matrix")
print(rot1)
print("translation vector:")
print(transl1)
print("If you take an atome situated in:[0.5 0.5 0]")
print("\nThen applying the 16th symmetry operation on that atom gives you another situated in:")
#matrix product
print("\n",dot(rot1, [0.5,0.5,0]) + transl1)


roto-inversion

rotation matrix
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
translation vector:
[0. 0. 0.]
If you take an atome situated in:[0.5 0.5 0]

Then applying the 10th symmetry operation on that atom gives you another situated in:

 [0.  0.5 0.5]


In [5]:
#
symop2 = symop[2] 
rot2 = symop2.rotation_matrix
trans2 = symop2.translation_vector
print("C2 axis")
print("rotation matrix")
print(rot2)
print("translation vector:")
print(trans2)
print("If you take an atome situated in:",site[1].species, site[1].frac_coords)
print("\nThen applying the 2nd symmetry operation on that atom gives you another situated in:")
#matrix product
print("\n",dot(rot2, site[1].frac_coords) + trans2)

rotation matrix
[[ 0. -1.  0.]
 [-1.  0.  0.]
 [ 0.  0. -1.]]
translation vector:
[0. 0. 0.]
If you take an atome situated in: Cl1 [0.75 0.75 0.75]

Then applying the 4th symmetry operation on that atom gives you another situated in:

 [-0.75 -0.75 -0.75]


In [28]:
#
symop3 = symop[7] 
rot3 = symop3.rotation_matrix
trans3 = symop3.translation_vector
print("(roto-inversion)")
print("\nrotation matrix")
print(rot3)
print("translation vector:")
print(trans3)
print("If you take an atome situated in:",site[2].species, site[2].frac_coords)
print("\nThen applying the 7th symmetry operation on that atom gives you another situated in:")
#matrix product
print("\n",dot(rot3, site[2].frac_coords) + trans3)

rotation matrix
[[ 0.  0.  1.]
 [-1. -1. -1.]
 [ 0.  1.  0.]]
translation vector:
[0. 0. 0.]
If you take an atome situated in: Cl1 [0.25 0.25 0.25]

Then applying the 47th symmetry operation on that atom gives you another situated in:

 [ 0.25 -0.75  0.25]
